name: CoarseDirtGuard
version: '${project.version}'
main: com.franchino961.coarsedirtguard.CoarseDirtGuard
api-version: 1.18
author: Franchino961
description: Prevents coarse dirt from being converted into dirt paths.